# This configuration was used Ebert to review the ma2gedev/power_assert_ex repository
# on 668343ba3734a20115b670d4a7ccabe5566ffcbd.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- test

